Task/urls.py
from django.conf.urls import url
from Task import views
# SET THE NAMESPACE!
app_name = 'Task'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^index/$', views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^task/$', views.task,name='task'),
    url(r'^tasksave/$', views.tasksave,name='tasksave'),
    url(r'^show/$', views.show,name='show'),
    url(r'^Eshow/$', views.Eshow,name='Eshow'),
]


TaskMaintenance/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Task import views
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^Task/', include('Task.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]
   

Task/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from _warnings import default_action

# Create your models here.

class Trainee(models.Model):  
    user = models.OneToOneField(User,on_delete=models.CASCADE)  
    Full_Name = models.CharField(max_length=100)
    Age = models.IntegerField()  
    Qualification = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username
          
    class Meta:  
        db_table = "traineedetails"
class sessionDetails(models.Model):
    tid = models.ForeignKey(User,default = 1)
    Date = models.DateField()
    session1 = models.CharField(max_length=200)
    session2 = models.CharField(max_length=200)
    session3 = models.CharField(max_length=200)
    session4 = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    
    class Meta:
        db_table = "sessiondetails"
class evaluation(models.Model):
    Eid = models.ForeignKey(User,default = 1)
    NamingConvertion = models.IntegerField()
    validationUse = models.IntegerField()
    exceptionUse = models.IntegerField()
    functionalityUse=models.IntegerField()
    InternetUsage =  models.IntegerField()
    UIdesign =  models.IntegerField()
    AdditionalTask =  models.IntegerField()
    communication =  models.IntegerField()
    logicalSkill =  models.IntegerField()
    debug =  models.IntegerField()
    coding =  models.IntegerField()
    TaskCompletion=models.IntegerField()
    
    class Meta:
        db_table = "evaluation"

Task/forms.py
from django import forms
from Task.models import Trainee,sessionDetails,evaluation
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class TraineeForm(forms.ModelForm):  
    class Meta:  
        model = Trainee 
        fields = ('Full_Name','Age','Qualification','profile_pic') 

class TaskForm(forms.ModelForm):
    #tid = forms.CharField(widget = forms.HiddenInput(),initial= User)
    Date = forms.DateField()
    class Meta:
        model = sessionDetails
        fields = ('Date','session1','session2','session3','session4','description')
class evaluateForm(forms.ModelForm):  
    class Meta:  
        model = evaluation  
        fields = "__all__"

Task/views.py
from django.shortcuts import render, redirect, render_to_response
from Task.forms import UserForm,TraineeForm,TaskForm
from Task.models import sessionDetails,evaluation
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
def index(request):
    return render(request,'index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
@csrf_exempt
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = TraineeForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = TraineeForm()
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
@csrf_exempt
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})
def task(request):
    form = TaskForm() 
    return render(request,'Tindex.html',{'form':form})
         
@csrf_exempt
def tasksave(request):  
    if request.method == 'POST': 
        form =TaskForm(request.POST, files=request.FILES)
        if form.is_valid():    
            instance = form.save(commit=False)
            instance.tid = request.user
            instance.save()
            return HttpResponseRedirect('../index')            
    else:        
        form = TaskForm()   
    
def show(request): 
   username = None
   if request.user.is_authenticated():
        username = request.user.username 
        Task_detailss = sessionDetails.objects.filter(tid__username = username)
        return render(request,'show.html',{'Task_detailss':Task_detailss}) 
def Eshow(request): 
   username = None
   if request.user.is_authenticated():
        username = request.user.username 
        evaluate = evaluation.objects.filter(Eid__username = username)
        return render(request,'Eshow.html',{'evaluate':evaluate}) 

Task/templates/Eshow.html
{% extends 'base.html' %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
table {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

table td, table th {
  border: 1px solid #ddd;
  padding: 8px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: hsl(147, 50%, 47%);
  color: white;
</style>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>   
        <th>NamingConvertion</th>  
        <th>validationUse</th>  
        <th>exceptionUse</th>  
        <th>functionalityUse</th>  
        <th>InternetUsage</th>
        <th>UIdesign</th>
        <th>AdditionalTask</th>
        <th>communication</th>
        <th>debug</th>
        <th>coding</th>
        <th>TaskCompletion</th>
       
    </tr>  
    </thead>  
    <tbody>  
{% for form in evaluate %}  
    <tr> 
        <td>{{ form.NamingConvertion }}</td> 
        <td>{{ form.validationUse }}</td> 
        <td>{{ form.exceptionUse }}</td> 
        <td>{{ form.functionalityUse }}</td> 
        <td>{{ form.InternetUsage }}</td> 
        <td>{{ form.UIdesign }}</td> 
        <td>{{ form.AdditionalTask }}</td> 
        <td>{{ form.communication }}</td> 
        <td>{{ form.debug }}</td> 
        <td>{{ form.coding }}</td>  
        <td>{{ form.TaskCompletion }}</td>  
	       
    </tr>  
{% endfor %}
</tbody>  
</table>  
<br>  
<br>  
<center><a href="{% url 'Task:index' %}"class="btn btn-primary">Back</a></center>
{% endblock %}

Task/templates/Tindex.html
{% extends 'base.html' %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">
  <div class="jumbotron">
 <style>
 input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
  border: 2px solid white;
  border-radius: 2px;
}
</style> 
</head>  
<body bgcolor= #FAEBD7>  
<form method="POST" class="post-form" action="{% url 'Task:tasksave' %}">  
        {% csrf_token %} 
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Fill Your session Details</h3>  
    </div>  
  	</div>  
    <div class="form-group row">  
    <label class="col-sm-3 col-form-label">Date:</label>  
    <div class="col-sm-4"> 
      <input type="Date" name="Date" placeholder="YYYY-MM-DD">
    </div>  
  </div>  
    <div class="form-group row">  
   <label class="col-sm-3 col-form-label">Session1 [9:30-11:30]:</label>  
    <div class="col-sm-5">  
     {{ form.session1 }}  
    </div>  
  </div> 
  <div class="form-group row">  
   <label class="col-sm-3 col-form-label">Session2[11:45-1:00]:</label>  
    <div class="col-sm-5">  
     {{ form.session2 }}  
    </div>  
  </div> 
  <div class="form-group row">  
   <label class="col-sm-3 col-form-label">Session3 [2:00-4:00]:</label>  
    <div class="col-sm-5">  
     {{ form.session3 }}  
    </div>  
  </div> 
  <div class="form-group row">  
   <label class="col-sm-3 col-form-label">Session4 [4:00-6:30]:</label>  
    <div class="col-sm-5">  
     {{ form.session4 }}  
    </div>  
  </div> 
  	<div class="form-group row">  
   <label class="col-sm-3 col-form-label">Description:</label>  
    <div class="col-sm-5">  
     {{ form.description }}  
    </div>  
  </div>
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
   </div>  
   </div>  
</form> 
</body>
{% endblock %}



Task/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">COOKIES</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'Task:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'Task:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Task/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Cookies Training !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <form action="{% url 'Task:task' %}">
        <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Enter Session Details</button>
        </div>
        </form>
        
        <form action="{% url 'Task:show' %}">
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-primary">Show Details</button>
         </div> 
        </form>
        
        <form action="{% url 'Task:Eshow' %}">
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-primary">Mark Details</button>
         </div> 
        </form>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
        
 	 {% endif  %}
  </div>
</div>
{% endblock %}

Task/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'Task:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          	<label for="username">Username:</label>
          	<input type="text" name="username" placeholder="Username">
			<label for="password">Password:</label>
          	<input type="password" name="password" placeholder="Password">
			<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

Task/templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
		<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

Task/templates/show.html
{% extends 'base.html' %}
{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
table {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

table td, table th {
  border: 1px solid #ddd;
  padding: 8px;
}

table tr:nth-child(even){background-color: #f2f2f2;}

table tr:hover {background-color: #ddd;}

table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: hsl(147, 50%, 47%);
  color: white;
</style>
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>   
        <th>Training Id</th>  
        <th>Date</th>  
        <th>Session1</th>
        <th>Session2</th>
        <th>Session3</th>
        <th>Session4</th>
        <th>Description</th>
    </tr>  
    </thead>  
    <tbody>  
{% for Task_details in Task_detailss %} 
		
		<tr>
	        <td>{{ Task_details.tid }}</td>  
	        <td>{{ Task_details.Date }}</td>  
	        <td>{{ Task_details.session1 }}</td>
	        <td>{{ Task_details.session2 }}</td>
	        <td>{{ Task_details.session3 }}</td>
	        <td>{{ Task_details.session4 }}</td>
	        <td>{{ Task_details.description }}</td> 
	       
    </tr>  
{% endfor %}
</tbody>  
</table>  
<br>  
<br>  
<center><a href="{% url 'Task:index' %}"class="btn btn-primary">Back</a></center>
{% endblock %}